export const LEADERBOARD = 'LEADERBOARD';
export const DONATION = 'DONATION';
export const CONGRATULATIONS = 'CONGRATULATIONS';
export const LOADING = 'LOADING';
export const CONNECT_WALLET = 'CONNECT_WALLET';
